version: "3.8"

services:
  frontend:
    container_name: mhaccgdb-frontend
    restart: always
    image: mhaccgdb-frontend
    build: 
        context: ./
    volumes:
      - ./:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mhaccgdb.entrypoints=web"
      - "traefik.http.services.mhaccgdb.loadbalancer.server.port=8080"
      - "traefik.http.routers.mhaccgdb.rule=PathPrefix(`/mhaccgdb`)"
    networks:
      - web
    command: ["yarn", "serve"]
  
networks:
  web:
    driver: bridge
    external: true
    name: web